"""Lexicons for the no-fabrication checker (specs/017 "No-fabrication rule").

Data, grown like ``ats_rules.py``. ``apply/factcheck.py`` reads it; nothing here decides.

- ``CLAIM_CLASSES``: an output word from a class that no cited line uses is a stronger claim
  than the source supports ("contributed to the migration" -> "led the migration").
- ``CREDENTIALS``: credential words that must appear in a cited line.
- ``TECH``: technology names checked against the whole resume (a skill or technology that is
  not anywhere in the resume fails); ``SYNONYMS`` maps aliases to one canonical name.
"""

from __future__ import annotations

import re

# Each class: plain words (matched as whole words, with simple inflections) and regexes.
CLAIM_CLASSES: dict[str, tuple[str, ...]] = {
    "leadership": (
        "led",
        "lead",
        "leading",
        "manage",
        "managed",
        "managing",
        "owned",
        "owning",
        "headed",
        "directed",
        "directing",
        "supervised",
        "supervising",
        "spearheaded",
        "drove",
        "oversaw",
        "overseeing",
    ),
    "scope": (
        "architected",
        "architect",
        "designed the",
        "founded",
        "founder",
        "co-founded",
        "built the team",
        "company-wide",
        "organization-wide",
        "org-wide",
        "end-to-end",
        "single-handedly",
    ),
    "superlative": (
        "expert",
        "expertise",
        "best",
        "first",
        "sole",
        "top",
        "world-class",
        "renowned",
        "unparalleled",
        "exceptional",
    ),
}
# Team-size claims are patterns, not words.
TEAM_SIZE = re.compile(
    r"\b(team of \d+|\d+[- ](person|people|member|engineer|engineers|developers|reports|direct "
    r"reports|staff)|(\d+|several|many) (engineers|developers|reports|direct reports|people))\b"
)

CREDENTIALS: tuple[str, ...] = (
    "certified",
    "certification",
    "certificate",
    "licensed",
    "license",
    "licence",
    "clearance",
    "secret clearance",
    "top secret",
    "ts/sci",
    "degree",
    "bachelor",
    "bachelors",
    "bachelor's",
    "master",
    "masters",
    "master's",
    "phd",
    "ph.d",
    "doctorate",
    "mba",
    "cpa",
    "pmp",
    "cissp",
    "ccna",
    "rhce",
    "accredited",
)

# Canonical technology names (lowercase). Not exhaustive: an unknown name is simply not checked
# in prose; every `skills` entry is checked against the resume regardless of this table.
TECH: tuple[str, ...] = (
    "ansible",
    "apache",
    "aws",
    "azure",
    "bash",
    "c#",
    "c++",
    "cassandra",
    "chef",
    "circleci",
    "cloudformation",
    "datadog",
    "django",
    "docker",
    "elasticsearch",
    "fastapi",
    "flask",
    "gcp",
    "git",
    "github actions",
    "gitlab",
    "go",
    "grafana",
    "graphql",
    "hadoop",
    "helm",
    "java",
    "javascript",
    "jenkins",
    "jira",
    "kafka",
    "kotlin",
    "kubernetes",
    "linux",
    "mongodb",
    "mysql",
    "nginx",
    "node.js",
    "openshift",
    "oracle",
    "perl",
    "php",
    "postgresql",
    "powershell",
    "prometheus",
    "puppet",
    "python",
    "rabbitmq",
    "react",
    "redis",
    "ruby",
    "rust",
    "salesforce",
    "sap",
    "scala",
    "snowflake",
    "spark",
    "splunk",
    "sql",
    "sql server",
    "swift",
    "tableau",
    "terraform",
    "typescript",
    "vmware",
    "windows server",
)
SYNONYMS: dict[str, str] = {
    "k8s": "kubernetes",
    "kube": "kubernetes",
    "golang": "go",
    "postgres": "postgresql",
    "psql": "postgresql",
    "js": "javascript",
    "ts": "typescript",
    "node": "node.js",
    "nodejs": "node.js",
    "amazon web services": "aws",
    "google cloud": "gcp",
    "google cloud platform": "gcp",
    "microsoft azure": "azure",
    "elastic": "elasticsearch",
    "mssql": "sql server",
    "ms sql": "sql server",
    "gha": "github actions",
    "tf": "terraform",
    "rhel": "linux",
    "red hat": "linux",
    "ubuntu": "linux",
    "debian": "linux",
    "centos": "linux",
}

NUMBER_WORDS: dict[str, str] = {
    "one": "1",
    "two": "2",
    "three": "3",
    "four": "4",
    "five": "5",
    "six": "6",
    "seven": "7",
    "eight": "8",
    "nine": "9",
    "ten": "10",
    "eleven": "11",
    "twelve": "12",
    "fifteen": "15",
    "twenty": "20",
    "thirty": "30",
    "fifty": "50",
    "hundred": "100",
}

# Tokens of an employer name that never identify it ("the", "inc", "state of").
EMPLOYER_STOP = {
    "the",
    "of",
    "and",
    "inc",
    "llc",
    "ltd",
    "co",
    "corp",
    "corporation",
    "company",
    "group",
    "state",
    "department",
    "dept",
    "county",
    "city",
    "university",
    "services",
    "service",
    "technologies",
    "technology",
    "systems",
    "solutions",
    "us",
    "usa",
    "america",
    "american",
    "national",
}
